"""Persist and read offline pseudo labels generated by ONNX teacher."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple

import numpy as np


@dataclass(frozen=True)
class SegmentPseudoLabel:
    clip_id: str
    segment_idx: int
    logits: np.ndarray


@dataclass(frozen=True)
class ClipPseudoLabel:
    clip_id: str
    agg_logits: np.ndarray
    hard_label: int
    confidence: float


def save_pseudo_labels_npz(
    output_path: str | Path,
    segment_labels: Sequence[SegmentPseudoLabel],
    clip_labels: Sequence[ClipPseudoLabel],
) -> None:
    output_path = Path(output_path)

    clip_ids = np.array([x.clip_id for x in segment_labels], dtype=object)
    segment_indices = np.array([x.segment_idx for x in segment_labels], dtype=np.int64)
    logits = np.stack([x.logits.astype(np.float32) for x in segment_labels], axis=0)

    agg_clip_ids = np.array([x.clip_id for x in clip_labels], dtype=object)
    agg_logits = np.stack([x.agg_logits.astype(np.float32) for x in clip_labels], axis=0)
    hard_labels = np.array([x.hard_label for x in clip_labels], dtype=np.int64)
    confidences = np.array([x.confidence for x in clip_labels], dtype=np.float32)

    np.savez_compressed(
        output_path,
        clip_ids=clip_ids,
        segment_indices=segment_indices,
        logits=logits,
        agg_clip_ids=agg_clip_ids,
        agg_logits=agg_logits,
        hard_labels=hard_labels,
        confidences=confidences,
    )


class PseudoLabelStore:
    """In-memory lookup structure for segment/clip pseudo labels."""

    def __init__(self, npz_path: str | Path):
        npz_path = Path(npz_path)
        if not npz_path.exists():
            raise FileNotFoundError(f"Pseudo labels not found: {npz_path}")

        raw = np.load(npz_path, allow_pickle=True)

        self.num_classes = int(raw["logits"].shape[1])
        self._segment_logits: Dict[Tuple[str, int], np.ndarray] = {}
        self._clip_logits: Dict[str, np.ndarray] = {}
        self._clip_hard: Dict[str, int] = {}
        self._clip_conf: Dict[str, float] = {}

        for clip_id, segment_idx, logits in zip(
            raw["clip_ids"], raw["segment_indices"], raw["logits"]
        ):
            self._segment_logits[(str(clip_id), int(segment_idx))] = logits.astype(np.float32)

        for clip_id, agg_logits, hard_label, confidence in zip(
            raw["agg_clip_ids"],
            raw["agg_logits"],
            raw["hard_labels"],
            raw["confidences"],
        ):
            key = str(clip_id)
            self._clip_logits[key] = agg_logits.astype(np.float32)
            self._clip_hard[key] = int(hard_label)
            self._clip_conf[key] = float(confidence)

    def get_segment_logits(self, clip_id: str, segment_idx: int) -> np.ndarray:
        return self._segment_logits[(clip_id, segment_idx)]

    def get_clip_logits(self, clip_id: str) -> np.ndarray:
        return self._clip_logits[clip_id]

    def get_clip_hard_label(self, clip_id: str) -> int:
        return self._clip_hard[clip_id]

    def get_clip_confidence(self, clip_id: str) -> float:
        return self._clip_conf[clip_id]

    def has_segment(self, clip_id: str, segment_idx: int) -> bool:
        return (clip_id, segment_idx) in self._segment_logits

    def clip_ids(self) -> Iterable[str]:
        return self._clip_logits.keys()
